use std::io::{BufRead, BufReader, Read, Write};
use std::path::PathBuf;
use std::process::{Command, Stdio};

use anyhow::{Context, Result, bail};
use portable_pty::{CommandBuilder, PtySize, native_pty_system};

/// Invocation guards described in a **tool-agnostic** way. Each [`Executor`]
/// impl translates these into its tool's flags. Switching tools = a new impl
/// that maps `ExecFlags` differently.
#[derive(Debug, Clone, Default)]
pub struct ExecFlags {
    /// Tools to block (e.g. merge). In Claude Code this becomes `--disallowedTools`.
    pub disallowed_tools: Vec<String>,
    /// Explicitly allowed tools (read-only review restricts to these).
    pub allowed_tools: Vec<String>,
    /// Extra system prompt text (constraints go here).
    pub append_system_prompt: Option<String>,
    /// Settings file registering the PreToolUse hook (generated by play).
    pub settings: Option<PathBuf>,
    /// Model override.
    pub model: Option<String>,
    /// Working directory (the task's worktree).
    pub cwd: Option<PathBuf>,
    /// Deterministic UUID of the session to CREATE (`--session-id`). Lets us
    /// resume later without parsing the output.
    pub session_id: Option<String>,
    /// UUID of the session to RESUME (`--resume`). Overrides `session_id`.
    pub resume: Option<String>,
    /// Escape hatch for extra flags.
    pub extra: Vec<String>,
}

impl ExecFlags {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn with_disallowed<I, S>(mut self, tools: I) -> Self
    where
        I: IntoIterator<Item = S>,
        S: Into<String>,
    {
        self.disallowed_tools
            .extend(tools.into_iter().map(Into::into));
        self
    }

    pub fn with_allowed<I, S>(mut self, tools: I) -> Self
    where
        I: IntoIterator<Item = S>,
        S: Into<String>,
    {
        self.allowed_tools.extend(tools.into_iter().map(Into::into));
        self
    }

    pub fn with_append_system_prompt(mut self, text: impl Into<String>) -> Self {
        self.append_system_prompt = Some(text.into());
        self
    }

    /// Registers the settings json that loads the PreToolUse hook (`enforce: hook` constraints).
    pub fn with_hook(mut self, settings: impl Into<PathBuf>) -> Self {
        self.settings = Some(settings.into());
        self
    }

    pub fn with_model(mut self, model: impl Into<String>) -> Self {
        self.model = Some(model.into());
        self
    }

    pub fn with_cwd(mut self, cwd: impl Into<PathBuf>) -> Self {
        self.cwd = Some(cwd.into());
        self
    }

    /// Creates the session with a known UUID (`--session-id`).
    pub fn with_session_id(mut self, id: impl Into<String>) -> Self {
        self.session_id = Some(id.into());
        self
    }

    /// Resumes an existing session (`--resume`).
    pub fn with_resume(mut self, id: impl Into<String>) -> Self {
        self.resume = Some(id.into());
        self
    }

    /// Translates to `claude` CLI args (without `--print` or the prompt).
    /// Variadic lists come before valued flags; the prompt never follows a
    /// variadic list (it's always positional at the start) so it isn't
    /// swallowed by `--disallowedTools a b <prompt>`.
    fn to_claude_args(&self) -> Vec<String> {
        let mut a = Vec::new();
        if !self.disallowed_tools.is_empty() {
            a.push("--disallowedTools".to_string());
            a.extend(self.disallowed_tools.iter().cloned());
        }
        if !self.allowed_tools.is_empty() {
            a.push("--allowedTools".to_string());
            a.extend(self.allowed_tools.iter().cloned());
        }
        if let Some(s) = &self.append_system_prompt {
            a.push("--append-system-prompt".to_string());
            a.push(s.clone());
        }
        if let Some(p) = &self.settings {
            a.push("--settings".to_string());
            a.push(p.to_string_lossy().into_owned());
        }
        if let Some(m) = &self.model {
            a.push("--model".to_string());
            a.push(m.clone());
        }
        // resume and session-id are mutually exclusive: resume wins over create.
        if let Some(r) = &self.resume {
            a.push("--resume".to_string());
            a.push(r.clone());
        } else if let Some(s) = &self.session_id {
            a.push("--session-id".to_string());
            a.push(s.clone());
        }
        a.extend(self.extra.iter().cloned());
        a
    }
}

/// Pluggable executor. play/review use `spawn_interactive`; ingest uses
/// `spawn_oneshot`. Keeps the core agnostic to which tool runs.
pub trait Executor {
    /// Runs once headless and returns stdout (ingest, `claude -p`).
    fn spawn_oneshot(&self, prompt: &str, flags: &ExecFlags) -> Result<String>;

    /// Opens an interactive session in a PTY (iterative play/review).
    fn spawn_interactive(&self, prompt: &str, flags: &ExecFlags) -> Result<Session>;

    /// Like `spawn_oneshot`, but calls `on_line` for each stdout line while the
    /// process runs (live logs). Returns the full stdout. The default (for
    /// fakes) just delegates to `spawn_oneshot` without streaming.
    fn spawn_oneshot_streaming(
        &self,
        prompt: &str,
        flags: &ExecFlags,
        on_line: &mut dyn FnMut(&str),
    ) -> Result<String> {
        let out = self.spawn_oneshot(prompt, flags)?;
        for line in out.lines() {
            on_line(line);
        }
        Ok(out)
    }
}

/// [`Executor`] impl for Claude Code (the `claude` CLI).
pub struct ClaudeExecutor {
    bin: String,
}

impl Default for ClaudeExecutor {
    fn default() -> Self {
        Self::new()
    }
}

impl ClaudeExecutor {
    pub fn new() -> Self {
        Self {
            bin: "claude".to_string(),
        }
    }

    /// Points to an alternative binary (used in tests).
    pub fn with_bin(bin: impl Into<String>) -> Self {
        Self { bin: bin.into() }
    }
}

impl Executor for ClaudeExecutor {
    fn spawn_oneshot(&self, prompt: &str, flags: &ExecFlags) -> Result<String> {
        let mut cmd = Command::new(&self.bin);
        // positional prompt first, then --print and the flags
        cmd.arg(prompt).arg("--print").args(flags.to_claude_args());
        if let Some(cwd) = &flags.cwd {
            cmd.current_dir(cwd);
        }
        let out = cmd
            .output()
            .with_context(|| format!("running {} --print", self.bin))?;
        if !out.status.success() {
            let stderr = String::from_utf8_lossy(&out.stderr);
            let stdout = String::from_utf8_lossy(&out.stdout);
            // with --output-format json the error goes to stdout as an envelope;
            // extract the `result` field for a clean message.
            let detail = if !stderr.trim().is_empty() {
                stderr.trim().to_string()
            } else if let Some(msg) = serde_json::from_str::<serde_json::Value>(stdout.trim())
                .ok()
                .and_then(|v| v.get("result").and_then(|r| r.as_str()).map(str::to_string))
            {
                msg
            } else {
                stdout.trim().to_string()
            };
            bail!(
                "{} --print failed (exit {:?}): {detail}",
                self.bin,
                out.status.code()
            );
        }
        Ok(String::from_utf8_lossy(&out.stdout).into_owned())
    }

    fn spawn_oneshot_streaming(
        &self,
        prompt: &str,
        flags: &ExecFlags,
        on_line: &mut dyn FnMut(&str),
    ) -> Result<String> {
        let mut cmd = Command::new(&self.bin);
        cmd.arg(prompt).arg("--print").args(flags.to_claude_args());
        if let Some(cwd) = &flags.cwd {
            cmd.current_dir(cwd);
        }
        cmd.stdout(Stdio::piped()).stderr(Stdio::piped());
        let mut child = cmd
            .spawn()
            .with_context(|| format!("running {} --print (stream)", self.bin))?;

        // stderr on a thread so we don't deadlock when its buffer fills.
        let stderr = child.stderr.take();
        let err_handle = std::thread::spawn(move || {
            let mut s = String::new();
            if let Some(mut e) = stderr {
                let _ = e.read_to_string(&mut s);
            }
            s
        });

        let stdout = child.stdout.take().context("no stdout from claude")?;
        let reader = BufReader::new(stdout);
        let mut full = String::new();
        for line in reader.lines() {
            let line = line.context("reading claude stdout")?;
            on_line(&line);
            full.push_str(&line);
            full.push('\n');
        }

        let status = child.wait().context("waiting for claude to exit")?;
        let stderr = err_handle.join().unwrap_or_default();
        if !status.success() {
            // with stream-json the error usually comes in the last `result`
            // event; use stderr if it has anything, else the raw stdout.
            let detail = if !stderr.trim().is_empty() {
                stderr.trim().to_string()
            } else {
                full.trim().to_string()
            };
            bail!(
                "{} --print (stream) failed (exit {:?}): {detail}",
                self.bin,
                status.code()
            );
        }
        Ok(full)
    }

    fn spawn_interactive(&self, prompt: &str, flags: &ExecFlags) -> Result<Session> {
        let pty = native_pty_system();
        let pair = pty.openpty(PtySize::default()).context("opening PTY")?;

        let mut cmd = CommandBuilder::new(&self.bin);
        if !prompt.is_empty() {
            cmd.arg(prompt); // positional first
        }
        for arg in flags.to_claude_args() {
            cmd.arg(arg);
        }
        if let Some(cwd) = &flags.cwd {
            cmd.cwd(cwd);
        }

        let child = pair
            .slave
            .spawn_command(cmd)
            .with_context(|| format!("starting {} session", self.bin))?;
        let writer = pair.master.take_writer().context("getting PTY writer")?;

        // Drop the slave: without this the reader never gets EOF when the child exits.
        drop(pair.slave);

        Ok(Session {
            child,
            master: pair.master,
            writer: Some(writer),
        })
    }
}

/// A live interactive session on a PTY. The executor owns the lifecycle; the
/// TUI reads from [`Session::reader`] and renders via vt100/tui-term.
pub struct Session {
    child: Box<dyn portable_pty::Child + Send + Sync>,
    master: Box<dyn portable_pty::MasterPty + Send>,
    writer: Option<Box<dyn Write + Send>>,
}

impl Session {
    /// Writes raw bytes to the session's stdin.
    pub fn write_input(&mut self, bytes: &[u8]) -> Result<()> {
        let w = self
            .writer
            .as_mut()
            .context("session input already closed")?;
        w.write_all(bytes).context("writing to PTY")?;
        w.flush().context("flushing PTY")?;
        Ok(())
    }

    /// Writes a line followed by CR (Enter on the PTY).
    pub fn write_line(&mut self, line: &str) -> Result<()> {
        self.write_input(line.as_bytes())?;
        self.write_input(b"\r")
    }

    /// Closes stdin (EOF for the child).
    pub fn close_input(&mut self) {
        self.writer = None;
    }

    /// Clones a reader for the PTY output (the TUI consumes it on a thread).
    pub fn reader(&self) -> Result<Box<dyn Read + Send>> {
        self.master.try_clone_reader().context("cloning PTY reader")
    }

    pub fn resize(&self, rows: u16, cols: u16) -> Result<()> {
        self.master
            .resize(PtySize {
                rows,
                cols,
                ..Default::default()
            })
            .context("resizing PTY")
    }

    /// `Some(success)` if it already exited, `None` if still running.
    pub fn try_wait(&mut self) -> Result<Option<bool>> {
        Ok(self.child.try_wait()?.map(|s| s.success()))
    }

    /// Blocks until it exits; returns whether it exited successfully.
    pub fn wait(&mut self) -> Result<bool> {
        Ok(self.child.wait()?.success())
    }

    pub fn kill(&mut self) -> Result<()> {
        self.child.kill().context("killing session")
    }
}
