// Cross-language contract: the golden fixtures under
// crates/cli/tests/fixtures/sidecar/ are generated by the Rust serde types;
// this suite decodes the same files with the sidecar's parser so a wire
// change breaks on both sides.

import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, test } from "bun:test";
import { decodeLine, type Command, type Event } from "../src/protocol.js";

const FIXTURE_DIR = join(
  import.meta.dir,
  "../../crates/cli/tests/fixtures/sidecar",
);

function fixture(name: string): unknown {
  return JSON.parse(readFileSync(join(FIXTURE_DIR, `${name}.json`), "utf8"));
}

const EVENT_TYPES = new Set([
  "session",
  "text_delta",
  "tool_use",
  "tool_result",
  "permission_request",
  "done",
  "error",
  "pong",
]);

describe("golden fixtures", () => {
  test("every command fixture decodes through the sidecar parser", () => {
    const names = readdirSync(FIXTURE_DIR)
      .filter((f) => f.startsWith("command_") && f.endsWith(".json"))
      .map((f) => f.replace(/\.json$/, ""));
    expect(names.length).toBeGreaterThanOrEqual(6);
    for (const name of names) {
      const raw = JSON.stringify(fixture(name));
      const cmd: Command = decodeLine(raw);
      expect(["chat", "permission_response", "abort", "ping"]).toContain(
        cmd.type,
      );
    }
  });

  test("chat fixture carries the guarded turn shape", () => {
    const cmd = decodeLine(JSON.stringify(fixture("command_chat")));
    if (cmd.type !== "chat") throw new Error("expected a chat command");
    expect(cmd.session_id).toBe("11111111-1111-4111-8111-111111111111");
    expect(cmd.resume).toBeNull();
    expect(cmd.disallowed_tools).toContain("Bash(git merge)");
    expect(cmd.guard_patterns[0]).toEqual({
      pattern: "src/legacy/",
      reason: "do not touch src/legacy/",
    });
    expect(cmd.content[0]).toEqual({ type: "text", text: "do the thing" });
    expect(cmd.content[1]).toMatchObject({
      type: "image",
      source: { type: "base64", media_type: "image/png" },
    });

    const resumed = decodeLine(JSON.stringify(fixture("command_chat_resume")));
    if (resumed.type !== "chat") throw new Error("expected a chat command");
    expect(resumed.resume).toBe("11111111-1111-4111-8111-111111111111");
  });

  test("permission responses decode both verdicts", () => {
    const allow = decodeLine(
      JSON.stringify(fixture("command_permission_response_allow")),
    );
    if (allow.type !== "permission_response") throw new Error("bad type");
    expect(allow.decision).toEqual({ behavior: "allow" });

    const deny = decodeLine(
      JSON.stringify(fixture("command_permission_response_deny")),
    );
    if (deny.type !== "permission_response") throw new Error("bad type");
    expect(deny.decision.behavior).toBe("deny");
  });

  test("every event fixture matches the sidecar's event union", () => {
    const names = readdirSync(FIXTURE_DIR)
      .filter((f) => f.startsWith("event_") && f.endsWith(".json"))
      .map((f) => f.replace(/\.json$/, ""));
    expect(names.length).toBeGreaterThanOrEqual(8);
    for (const name of names) {
      const event = fixture(name) as Event;
      expect(EVENT_TYPES.has(event.type)).toBe(true);
      if (event.type !== "pong") {
        expect(typeof (event as { request_id: string }).request_id).toBe(
          "string",
        );
      }
    }
  });

  test("done and usage fields line up with what the sidecar emits", () => {
    const done = fixture("event_done") as Event;
    if (done.type !== "done") throw new Error("bad type");
    expect(done.usage).toEqual({
      input_tokens: 10,
      output_tokens: 5,
      cache_read_tokens: 3,
    });
    expect(done.stop_reason).toBe("end_turn");
  });
});
